import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import SideDrawer from "@/components/Navigation/Drawer";
import { Box, Toolbar } from "@mui/material";
const drawerWidth = 240;

export const metadata: Metadata = {
  title: "MongodiAPP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="it">
      <body>
        <Providers>
          <Box sx={{ display: "flex" }}>
            
            {/* SIDEBAR */}
            <SideDrawer />

            {/* CONTENUTO PRINCIPALE */}
            <Box
              component="main"
              sx={{
                flexGrow: 1,
                p: 3,
                width: `calc(100% - ${drawerWidth}px)`,
              }}
            >
              <Toolbar />
              {children}
            </Box>

          </Box>
        </Providers>
      </body>
    </html>
  );
}

